# Generated by Django 4.2.1 on 2024-03-29 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='link',
            field=models.URLField(default=django.utils.timezone.now, verbose_name='Event Link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/event/'),
        ),
    ]
