# Generated by Django 4.2.1 on 2023-05-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='thumb',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='desc',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterModelTable(
            name='images',
            table='Image',
        ),
        migrations.AlterModelTable(
            name='musics',
            table='Music',
        ),
        migrations.AlterModelTable(
            name='upcomingevents',
            table='Event',
        ),
        migrations.AlterModelTable(
            name='videos',
            table='Video',
        ),
    ]
