# Generated by Django 4.2.1 on 2023-10-04 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_videos_dur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musics',
            name='music',
            field=models.FileField(upload_to='musics/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'ogg', 'm4a', 'wma'])]),
        ),
    ]
