# Generated by Django 4.2.1 on 2024-02-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_imageforblog_videoforblog_alter_visitorcounter_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(related_name='image_for_blog', to='main.imageforblog'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.ManyToManyField(related_name='video_for_blog', to='main.videoforblog'),
        ),
    ]
