# Generated by Django 4.2.1 on 2024-02-19 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_post_image_remove_post_video_post_image_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='Contact',
        ),
        migrations.AlterModelTable(
            name='imageforblog',
            table='ImageForBlog',
        ),
        migrations.AlterModelTable(
            name='post',
            table='Post',
        ),
        migrations.AlterModelTable(
            name='subscribeemail',
            table='Email',
        ),
        migrations.AlterModelTable(
            name='videoforblog',
            table='VideoForBlog',
        ),
    ]
