# Generated by Django 4.2.1 on 2024-02-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contact_table_alter_imageforblog_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='medias',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
