# Generated by Django 4.2.1 on 2024-02-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_post_medias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='image_for_blog', to='main.imageforblog'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.ManyToManyField(blank=True, related_name='video_for_blog', to='main.videoforblog'),
        ),
    ]
