# Generated by Django 4.2.1 on 2024-02-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_post_image_alter_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='medias',
            field=models.IntegerField(default=0),
        ),
    ]
